### ISSUE TITLE
Use URI templates

### ISSUE THREAD

**Issue by justincy** [webshell/APIs#4]
[URI templates](http://tools.ietf.org/html/rfc6570) would greatly reduce the amount of argument/parameter processing that you need to do in endpoint functions, such as what's being done for [Flickr](https://github.com/webshell/APIs/blob/master/flickr/v0.1/flickr). Here' a nice JS implementation: https://github.com/fxa/uritemplate-js

Instead of making a ton of calls to `url_replace` you could use just one line of code:

``` javascript
url = UriTemplate.parse(url).expand(args);
```

**Comment by bumpmann** [comment]
Uri templates seems good for replacing in the url however the calls to url_replace allow to basic checking types, default parameters, replacing in url OR append to the querystring. We could only limit to url replacing but currently we are keeping these details.
